version: '1.0'
name: android-build
displayName: 暗区指令工具 云编译
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - main
stages:
  - name: build
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@gradle
        name: build_apk
        displayName: Android APK 构建
        jdkVersion: '21'
        gradleVersion: 9.5.1
        commands:
          - '# 功能：Android Debug 包构建'
          - 'set -e'
          - 'chmod +x ./gradlew'
          - './gradlew assembleDebug --no-daemon'
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./app/build/outputs/apk/debug
        settings: []
        caches:
          - ~/.gradle/caches
        notify: []
        strategy:
          retry: '0'
